<script>
        $(document).ready( function () {
    $('#data').DataTable();
} );
    </script>
<div id="content">

    <h1>View Attendance</h1>
    <p>Below is a list of all attendance records.</p>
    <table id="data">
        <thead>
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Time In</th>
                <th>Time Out</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Rafli</td>
                <td>2022-12-11</td>
                <td>8.45</td>
                <td>17.45</td>
            </tr>
            <tr>
                <td>Naufal</td>
                <td>2022-12-11</td>
                <td>8.01</td>
                <td>17.05</td>
            </tr>
            <tr>
                <td>Surya</td>
                <td>2022-12-11</td>
                <td>8.15</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr> <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
             <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr> <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr> <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
             <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr> <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr> <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            <tr>
                <td>Yasinta</td>
                <td>2022-12-11</td>
                <td>8.30</td>
                <td>17.30</td>
            </tr>
            
        </tbody>
    </table>
</div>